name: Android CI
on:
  push:
    branches: [main, master, "**"]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ./lab8
      - name: Build and test with Gradle
        run: ./gradlew build
        working-directory: ./lab8
